### ISSUE TITLE
`Is this backwards compatible?` section should mention breaking tagged template

### ISSUE THREAD

**Issue by fisker** [tc39/proposal-string-dedent#36]
This section only mentioned that ` ```abc``` ` will cause runtime error. 

> So no functioning code should be affected by this change.

This is not true.

```js
const foo = () => () => () => 'baz';
console.log(foo```bar```);
```

Through, I don't think anyone uses this, but I did think about build something like this, I didn't do it only because ` foo`` ` can achieve the same goal.

We should mention this use case.

**Comment by fisker** [comment]
Right, thanks.

**Comment by weitingweiting** [comment]
niubility
