### ISSUE TITLE
Why straight up three backticks? Why not just two?

### ISSUE THREAD

**Issue by tomasklaen** [tc39/proposal-string-dedent#39]
Two backticks won't collide with markdown or anything I can think of, and is simpler/less verbose to write.

**Comment by Qix-** [comment]
Two backticks are already syntactically valid - an empty string. It makes parsing ambiguous if they are both an empty string as well as a marker for new semantics. It'd potentially break existing code, too.

Three ticks are a syntax error now. You can't have two strings directly next to each other, much less three (empty tick string, potentially non-empty tick string, another empty tick string). Thus the three ticks can be safely used as a marker for new semantics, as I don't think anyone is interested in 'protecting' code that has syntax errors.

Lastly, the three ticks are almost certainly inspired by Python's multi-line strings, which are three quotes:

```python
print("""
This is a full string,
that can span multiple lines.
""")
```

**Comment by tomasklaen** [comment]
Fair enough :) Sorry for wasting time.

**Comment by jridgewell** [comment]
Additionally, markdown allows for [any number of backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to create a code block, eg, here's a 5 tick block that includes 3 and 4 ticks inside it:

`````
3-tick:
```
```

4-tick:
````
````
`````

**Comment by Qix-** [comment]
Oh yeah, missed the markdown comment :) Note that this doesn't work on every markdown parser (but it should).
