### ISSUE TITLE
Nesting template literals without escaping like raw string literals in C# 11

### ISSUE THREAD

**Issue by luncheon** [tc39/proposal-string-dedent#53]
There are cases where we'd like to evaluate a dynamic string as a script (e.g. using `eval()`, `Function()`, Node.js `vm` module, or `new ShadowRealm().evaluate()`). To include template literals in that script, delimiters need to be escaped. This is a bit hard to read.

```js
const question = "The answer to the Ultimate Question of Life";
eval(`
  const answer = 42;
  \`${question} is \${answer}.\\n\`;
`);
```

or

```js
const question = "The answer to the Ultimate Question of Life";
eval(String.raw`
  const answer = 42;
  ${"`"}${question} is ${"$"}{answer}.\n${"`"};
`);
```

C# 11's new “raw string literal” syntax is very useful for metaprogramming because they can be nested without escaping.
https://github.com/dotnet/csharplang/blob/main/proposals/raw-string-literal.md

What do you think about introducing a raw template literal syntax like this in ECMAScript?

`````js
const question = "The answer to the Ultimate Question of Life";
eval(@@````
  const answer = 42;
  ```
    $${question} is ${answer}.

  ```;
````);
`````

Have you completely given up on introducing new syntax?

**Comment by jridgewell** [comment]
Several committee members opposed adding new syntax for String.dedent, so I don't think it's likely we'll get it. It's possible that we can add new template syntaxes that aren't tied to dedenting behavior, but this would be a separate proposal.

`````js

const foo = """
  this isn't dedent, it's just a regular multiline string using a different syntax
""";

const bar = String.dedent"""
  this is a tagged string literal, and it'll dedent.
"""
```
